// listee-106/vuejs/src/views/pages/my-listing/MyListing.vue
<template>
	<!-- Dashboard Content -->
	<div class="dashboard-content">
		<div class="container">
			<div class="">
				<ul class="dashborad-menus">
					<li>
						<router-link to="/dashboard">
							<i class="feather-grid"></i> <span>Dashboard</span>
						</router-link>
					</li>
					<li>
						<router-link to="/profile">
							<i class="fa-solid fa-user"></i> <span>Profile</span>
						</router-link>
					</li>
					<li class="active">
						<router-link to="/my-listing">
							<i class="feather-list"></i> <span>My Listing</span>
						</router-link>
					</li>
					<li>
						<router-link to="/bookmarks">
							<i class="fas fa-solid fa-heart"></i> <span>Bookmarks</span>
						</router-link>
					</li>
					<li>
						<router-link to="/messages">
							<i class="fa-solid fa-comment-dots"></i> <span>Messages</span>
						</router-link>
					</li>
					<li>
						<router-link to="/reviews">
							<i class="fas fa-solid fa-star"></i> <span>Reviews</span>
						</router-link>
					</li>
					<li>
						<router-link to="login">
							<i class="fas fa-light fa-circle-arrow-left"></i> <span>Logout</span>
						</router-link>
					</li>
				</ul>
			</div>
			<div class="dash-listingcontent dashboard-info">
				<div class="dash-cards card">
					<div class="card-header">
						<h4>My Listings</h4>
						<router-link class="nav-link header-login add-listing" to="/add-listing"><i
								class="fa-solid fa-plus"></i> Add Listing</router-link>
					</div>
					<div class="card-body">
						<div class="listing-search">
							<div class="filter-content form-group">
								<div class="group-img">
									<input type="text" class="form-control" placeholder="Search...">
									<i class="feather-search"></i>
								</div>
							</div>
							<div class="sorting-div">
								<div class="sortbyset">
									<span class="sortbytitle">Sort by</span>
									<div class="sorting-select">
										<vue-select :options="Newest" placeholder="Newest" />
									</div>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<a-table
                    class="stripped table-hover listing-table datatable"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template
                        v-if="column.key === 'image'"
                      >
					  <div class="listingtable-img">
							<router-link to="/service-details">
								<img class="img-fluid avatar-img"
									:src="require(`../../../assets/img/list/${record.image}`)" alt="">
							</router-link>
						</div>
                      </template>
                      <template v-else-if="column.key === 'id'">
						<h6>
							<router-link to="/service-details">{{record.title}}</router-link>
						</h6>
						<div class="listingtable-rate">
							<a href="javascript:void(0)" class="cat-icon"><i
									class="fa-regular fa-circle-stop"></i>  Electronics </a> <span
								class="discount-amt">$350000.00</span><span
								class="fixed-amt">$40000</span>
						</div>
						<p>Mauris vestibulum lorem a condimentum vulputate</p>
                      </template>
                      <template v-else-if="column.key === 'status'">
                        <span :class="record.class">{{record.status}}</span>
                      </template>
					  <template v-else-if="column.key === 'views'">
                        <span class="views-count">{{record.views}}</span>
                      </template>
                      <template v-else-if="column.key === 'action'">
                        <div class="action">
							<a href="javascript:void(0)" class="action-btn btn-view"><i
									class="feather-eye"></i></a>
							<a href="javascript:void(0)" class="action-btn btn-edit"><i
									class="feather-edit-3"></i></a>
							<a href="javascript:void(0)" class="action-btn btn-trash"><i
									class="feather-trash-2"></i></a>
						</div>
                      </template>
                    </template>
                  </a-table>
					</div>
					<div class="blog-pagination">
						<nav>
							<ul class="pagination">
								<li class="page-item previtem">
									<a class="page-link" href="#"><i class="fas fa-regular fa-arrow-left"></i> Prev</a>
								</li>
								<li class="justify-content-center pagination-center">
									<div class="pagelink">
										<ul>
											<li class="page-item">
												<a class="page-link" href="#">1</a>
											</li>
											<li class="page-item active">
												<a class="page-link" href="#">2 <span
														class="visually-hidden">(current)</span></a>
											</li>
											<li class="page-item">
												<a class="page-link" href="#">3</a>
											</li>
										</ul>
									</div>
								</li>
								<li class="page-item nextlink">
									<a class="page-link" href="#">Next <i class="fas fa-regular fa-arrow-right"></i></a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Dashboard Content -->
</template>
<script>
const columns = [
  {
    title: "Image",
    dataIndex: "image",
    key: "image",
	sorter: {
      compare: (a, b) => {
        a = a.image.toLowerCase();
        b = b.image.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Details",
    dataIndex: "title",
	key: "id",
    sorter: {
      compare: (a, b) => {
        a = a.title.toLowerCase();
        b = b.title.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "status",
	key: "status",
    sorter: {
      compare: (a, b) => {
        a = a.status.toLowerCase();
        b = b.status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Views",
    dataIndex: "views",
    key: "views",
    sorter: {
      compare: (a, b) => {
        a = a.views.toLowerCase();
        b = b.views.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "action",
    class: "text-end",
    sorter: true,
  },
];

const data =[
    {
        id: 1,
        image: "tablelist-1.jpg",
        title: "Villa 457 sq.m. In Benidorm Fully Qquipped House",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 2,
        image: "tablelist-2.jpg",
        title: "CDL A OTR Compnay Driver Job-N",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 3,
        image: "tablelist-3.jpg",
        title: "HP Gaming 15.6 Touchscren 12G",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 4,
        image: "tablelist-4.jpg",
        title: "2012 AudiR8 GT Spider Convrtibile",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 5,
        image: "tablelist-5.jpg",
        title: "2017 Gulfsteam Ameri-Lite",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 6,
        image: "tablelist-6.jpg",
        title: "Fashion Luxury Men Date",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 7,
        image: "tablelist-7.jpg",
        title: "Apple iPhone 6 16GB 4G LTE",
        class: "status-text",
        status: "Published",
        views: "1523"
    },
    {
        id: 8,
        image: "tablelist-8.jpg",
        title: "Customized Apple iMac 21.5″ All-In",
        class: "status-text unpublish",
        status: "Un Published",
        views: "1523"
    }

]
export default {
	data() {
		return {
			
			Newest: ["Newest", "Newest", "Oldest"],
			data,
			columns,
		}
	}
}
</script>

// listee-106/reactjs/src/components/userPages/mylisting/index.jsx
import React from "react";

import Mylistings from "../../json/Mylisting"
import { Table } from "antd";
import { Link, useLocation } from "react-router-dom";
import Footer from "../../home/footer/Footer";
import UserHeader from "../Userheader";


const MyListe = () => {
    const data = Mylistings.Mylistings;
    const dataSource = {
        data,

    };

    const columns = [
        {
            title: 'Image',
            dataIndex: 'image',
            render: (text, record, data) => (


                <div className="listingtable-img">
                    {" "}
                    <Link to="/service-details">
                        <img
                            className="img-fluid avatar-img"
                            src={text}
                            alt=""
                        />
                    </Link>
                </div>

            ),
            sorter: (a, b) => { a.image.length - b.image.length }
        },
        {
            title: 'Details',
            dataIndex: 'content',
            render: (text, record, data) => (
                <>
                    <h6>
                        <Link to="/service-details">
                            {text}
                        </Link>
                    </h6>
                    <div className="listingtable-rate">
                        <Link to="#" className="cat-icon">
                            <i className="fa-regular fa-circle-stop" />{" "}
                            Electronics
                        </Link>{" "}
                        <span className="discount-amt">$350000.00</span>
                        <span className="fixed-amt">$40000</span>
                    </div>
                    <p>Mauris vestibulum lorem a condimentum vulputate.</p>
                </>
            ),
            sorter: (a, b) => { a.content.length - b.content.length }
        },
        {
            title: 'Status',
            dataIndex: 'status',
            render: (text, record, data) => (
                <span className={record.bg}>{text}</span>
            ),
            sorter: (a, b) => { a.status.length - b.status.length }
        },
        {
            title: 'Views',
            dataIndex: 'numbers',
            render: (text, record, data) => (
                <span>{text}</span>
            ),
            sorter: (a, b) => { a.numbers.length - b.numbers.length }
        },
        {
            title: 'Action',
            dataIndex: 'class',
            render: (text, record, data) => (
                <div className={text}>
                    <Link
                        to="#"
                        className="action-btn btn-view"
                    >
                        <i className="feather-eye" />
                    </Link>
                    <Link
                        to="#"
                        className="action-btn btn-edit"
                    >
                        <i className="feather-edit-3" />
                    </Link>
                    <Link
                        to="#"
                        className="action-btn btn-trash"
                    >
                        <i className="feather-trash-2" />
                    </Link>
                </div>
            ),
            sorter: (a, b) => { a.class.length - b.class.length }
        },


    ]
    const parms=useLocation().pathname
    return (
        <>
            <UserHeader parms={parms}/>
            {/* Breadscrumb Section */}
            <div className="breadcrumb-bar">
                <div className="container">
                    <div className="row align-items-center text-center">
                        <div className="col-md-12 col-12">
                            <h2 className="breadcrumb-title">My Listing</h2>
                            <nav aria-label="breadcrumb" className="page-breadcrumb">
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <Link to="/index">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active" aria-current="page">
                                        My Listing
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadscrumb Section */}
            {/* Dashboard Content */}
            <div className="dashboard-content">
                <div className="container">
                    <div className="">
                        <ul className="dashborad-menus">
                            <li>
                                <Link to="/dashboard">
                                    <i className="feather-grid" /> <span>Dashboard</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/profile">
                                    <i className="fa-solid fa-user" /> <span>Profile</span>
                                </Link>
                            </li>
                            <li className="active">
                                <Link to="/my-listing">
                                    <i className="feather-list" /> <span>My Listing</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/bookmarks">
                                    <i className="fas fa-solid fa-heart" /> <span>Bookmarks</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/messages">
                                    <i className="fa-solid fa-comment-dots" /> <span>Messages</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/reviews">
                                    <i className="fas fa-solid fa-star" /> <span>Reviews</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/login">
                                    <i className="fas fa-light fa-circle-arrow-left" />{" "}
                                    <span>Logout</span>
                                </Link>
                            </li>
                        </ul>
                    </div>
                    <div className="dash-listingcontent dashboard-info">
                        <div className="dash-cards card">
                            <div className="card-header">
                                <h4>My Listings</h4>
                                <Link
                                    className="nav-link header-login add-listing"
                                    to="/add-listing"
                                >
                                    <i className="fa-solid fa-plus" /> Add Listing
                                </Link>
                            </div>
                            <div className="card-body">
                                <div className="listing-search">
                                    <div className="filter-content form-group">
                                        <div className="group-img">
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="Search..."
                                            />
                                            <i className="feather-search" />
                                        </div>
                                    </div>
                                    <div className="sorting-div">
                                        <div className="sortbyset">
                                            <span className="sortbytitle">Sort by</span>
                                            <div className="sorting-select">
                                                <select className="form-control select">
                                                    <option>Newest</option>
                                                    <option>Newest</option>
                                                    <option>Oldest</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="table-responsive">
                                    
                                        <Table
                                            className="listing-table datatable"
                                            columns={columns}
                                            // bordered
                                            dataSource={data}
                                            rowKey={(record) => record.id}
                                            showSizeChanger={true}
                                            


                                        />
                                    
                                </div>
                                <div className="blog-pagination">
                                    <nav>
                                        <ul className="pagination">
                                            <li className="page-item previtem">
                                                <Link className="page-link" to="#">
                                                    <i className="fas fa-regular fa-arrow-left" /> Prev
                                                </Link>
                                            </li>
                                            <li className="justify-content-center pagination-center">
                                                <div className="pagelink">
                                                    <ul>
                                                        <li className="page-item">
                                                            <Link className="page-link" to="#">
                                                                1
                                                            </Link>
                                                        </li>
                                                        <li className="page-item active">
                                                            <Link className="page-link" to="#">
                                                                2 <span className="visually-hidden">(current)</span>
                                                            </Link>
                                                        </li>
                                                        <li className="page-item">
                                                            <Link className="page-link" to="#">
                                                                3
                                                            </Link>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </li>
                                            <li className="page-item nextlink">
                                                <Link className="page-link" to="#">
                                                    Next <i className="fas fa-regular fa-arrow-right" />
                                                </Link>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Dashboard Content */}
            <Footer/>
        </>

    );
}
export default MyListe;
