// listee-106/reactjs/src/components/pages/about/index.jsx
import React from "react";
import { about_img, australia_1, canada_1, china_1, cta_img, france_1, london_1, quotes, uk_1, usa_1 } from "../../imagepath";
import Cilent from "./silder/cilent";
import Sponcer from "./silder/sponcer";
import Footer from "../../home/footer/Footer";
import Header from "../../home/header";
import { Link, useLocation } from "react-router-dom";





const About = () => {
    const parms=useLocation().pathname
    console.log(parms,"aboutpage");
    return (
        <>
            <Header parms={parms}/>
            {/*Inner Banner*/}
            <div className="aboutbanner innerbanner">
                <div className="inner-breadcrumb">
                    <div className="container">
                        <div className="row align-items-center text-center">
                            <div className="col-md-12 col-12 ">
                                <h2 className="breadcrumb-title">About Us</h2>
                                <nav aria-label="breadcrumb" className="page-breadcrumb">
                                    <ol className="breadcrumb">
                                        <li className="breadcrumb-item">
                                            <Link to="/index">Home</Link>
                                        </li>
                                        <li className="breadcrumb-item active" aria-current="page">
                                            About us
                                        </li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/*/Inner Banner*/}
            {/*About Content*/}
            <section className="about-content">
                <div className="container">
                    <div className="about-listee">
                        <div className="about-img">
                            <img src={about_img} className="img-fluid" alt="" />
                        </div>
                        <div className="about-info">
                            <h4>
                                {" "}
                                <span>About</span> Listee
                            </h4>
                            <p>
                                Orci varius natoque penatibus et magnis dis parturient montes,
                                nascetur ridiculus mus. Nulla fermentum malesuada pulvinar.
                                Vestibulum laoreet rutrum semper. Vivamus malesuada, nisl in
                                consectetur semper, mauris nulla aliquam risus, nec ultricies sapien
                                elit sed ante. Aenean luctus felis in sem
                            </p>
                            <p>
                                Orci varius natoque penatibus et magnis dis parturient montes,
                                nascetur ridiculus mus. Nulla fermentum malesuada pulvinar.
                                Vestibulum laoreet rutrum semper. Vivamus malesuada,{" "}
                            </p>
                        </div>
                    </div>
                </div>
            </section>
            {/*/About Content*/}
            {/*How It Works*/}
            <section className="howitworks">
                <div className="container">
                    <h3>How It Work</h3>
                    <p>
                        Orci varius natoque penatibus et magnis dis parturient montes, nascetur
                        ridiculus mus. Nulla fermentum malesuada pulvinar. Vestibulum laoreet
                        rutrum semper. Vivamus malesuada, nisl in consectetur semper, mauris
                        nulla aliquam risus, nec ultricies sapien elit sed ante. Aenean luctus
                        felis in sem consequat auctor. Nulla turpis enim, scelerisque sit amet
                        consectetur vel, lacinia sed augue. Proin ultricies dui id ex fringilla
                        porta.
                    </p>
                    <p>
                        Morbi nisi justo, venenatis ac nibh at, bibendum mattis risus. Maecenas
                        tincidunt, ligula sed congue tempus, magna augue cursus ipsum, in
                        malesuada justo risus nec lorem. Nam augue augue, mollis nec condimentum
                        euismod, lacinia ultricies leo.
                    </p>
                    <div className="row">
                        <div className="col-lg-4 col-md-4 d-flex">
                            <div className="howitwork-info">
                                <h5>01</h5>
                                <h6>Create Account</h6>
                                <p>
                                    Morbi nisi justo, venenatis ac nibh at, bibendum mattis risus.
                                    Maecenas tincidunt, ligula sed congue tempus, magna augue cursus
                                    ipsum, in malesuada justo risus nec lorem. Nam augue augue, mollis
                                    nec condimentum euismod, lacinia ultricies leo.
                                </p>
                            </div>
                        </div>
                        <div className="col-lg-4 col-md-4 d-flex">
                            <div className="howitwork-info">
                                <h5>02</h5>
                                <h6>Post An Ad</h6>
                                <p>
                                    Morbi nisi justo, venenatis ac nibh at, bibendum mattis risus.
                                    Maecenas tincidunt, ligula sed congue tempus, magna augue cursus
                                    ipsum, in malesuada justo risus nec lorem. Nam augue augue, mollis
                                    nec condimentum euismod, lacinia ultricies leo.
                                </p>
                            </div>
                        </div>
                        <div className="col-lg-4 col-md-4 d-flex">
                            <div className="howitwork-info">
                                <h5>03</h5>
                                <h6>Find,Buy &amp; Own Dreams</h6>
                                <p>
                                    Morbi nisi justo, venenatis ac nibh at, bibendum mattis risus.
                                    Maecenas tincidunt, ligula sed congue tempus, magna augue cursus
                                    ipsum, in malesuada justo risus nec lorem. Nam augue augue, mollis
                                    nec condimentum euismod, lacinia ultricies leo.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/*/How It Works*/}
            {/*Popular Location*/}
            <div className="aboutpopular-locations">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-3 col-md-4">
                            <div className="aboutlocation-details usa">
                                <div className="aboutloc-img">
                                    <img src={london_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>London</h3>
                                        <span>20+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-4">
                            <div className="aboutlocation-details usa">
                                <div className="aboutloc-img">
                                    <img src={usa_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>USA</h3>
                                        <span>15+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-4">
                            <div className="aboutlocation-details canada">
                                <div className="aboutloc-img">
                                    <img src={canada_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>Canada</h3>
                                        <span>25+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                            <div className="aboutlocation-details china">
                                <div className="aboutloc-img">
                                    <img src={china_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>China</h3>
                                        <span>17+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                            <div className="aboutlocation-details uk">
                                <div className="aboutloc-img">
                                    <img src={uk_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>United Kingdom</h3>
                                        <span>12+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-6 col-md-6">
                            <div className="aboutlocation-details australi-loc">
                                <div className="aboutloc-img">
                                    <img src={australia_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>Australia</h3>
                                        <span>25+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                            <div className="aboutlocation-details france">
                                <div className="aboutloc-img">
                                    <img src={france_1} alt="" />
                                </div>
                                <Link to="/listing-grid-sidebar">
                                    <div className="aboutlocations-info">
                                        <h3>France</h3>
                                        <span>14+ Ads Posted</span>
                                    </div>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/*/Popular location*/}
            {/* CTA Section */}
            <section className="cta-section">
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-7">
                            <div className="cta-content">
                                <h3>
                                    Earn Cash by <span>Selling</span> <br />
                                    or Find Anything you desire
                                </h3>
                                <p>
                                    There are many variations of passages of Lorem Ipsum available,
                                    but the majority have suffered alteration in some form, by
                                    injected humo or randomised words which don't look even slightlys
                                </p>
                                <div className="cta-btn">
                                    <Link to="/add-listing" className="btn-primary postad-btn">
                                        Post Your Ads
                                    </Link>
                                    <Link to="/listing-grid-sidebar" className="browse-btn">
                                        Browse Ads
                                    </Link>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-5">
                            <div className="cta-img">
                                <img src={cta_img} className="img-fluid" alt="CTA" />
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* /CTA Section */}
            {/* Client Testimonilas Section */}
            <section className="testimonials-section">
                <div className="row">
                    <div className="col-lg-5">
                        <div className="testimonial-heading d-flex">
                            <h4>
                                {" "}
                                Client <br /> Testimonials
                            </h4>
                            <img src={quotes} alt="quotes" />
                        </div>
                    </div>
                    <div className="col-lg-7">
                        <div className="rightimg" />
                    </div>
                </div>
                <div className="container">
                    <div className="row">
                        <div className="testimonials-slidersection">
                            <div className="owl-nav mynav1" />
                            <Cilent />
                        </div>
                    </div>
                </div>
            </section>
            {/* /Client Testimonilas Section */}
            {/* Partners Section */}
            <div className="partners-section">
                <div className="container">
                    <p className="partners-heading">
                        Over 5,26,000+ Sponsers being contact with us
                    </p>
                    <Sponcer />
                </div>
            </div>
            {/* /Partners Section */}

            <Footer />
        </>

    );
}
export default About;

// listee-106/angular/src/app/featuremodule/pages/about/about.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/core/helpers/routes/routes';
import { DataService } from 'src/app/service/data.service';
import { OwlOptions } from 'ngx-owl-carousel-o';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent {
  public routes=routes;
  public testimonial:any=[];
  public universitiesCompanies:any=[]
  public accountcreation:any=[]
  constructor(private DataService:DataService){
    this.testimonial=this.DataService.testimonialList,
    this.universitiesCompanies=this.DataService.universitiesCompanies
    this.accountcreation=this.DataService.accountcreation
   

  }
  public testimonialOwlOptions:OwlOptions={
    loop:true,
    margin:24,
    nav:true,
    dots: false,
    smartSpeed: 2000,
    navText : ["<i class='fa-solid fa-angle-left'></i>","<i class='fa-solid fa-angle-right'></i>"],
    
    responsive:{
      0:{
        items:1
      },
      
      550:{
        items:1
      },
      700:{
        items:2
      },
      1000:{
        items:2
      }
    }
  }
  public universitiesCompaniesOwlOptions: OwlOptions = {
    loop:true,
    margin:24,
    nav:false,
    autoplay:true,
    smartSpeed: 2000,
    
    navText : ["<i class='fa-solid fa-angle-left'></i>","<i class='fa-solid fa-angle-right'></i>"],
    responsive:{
      0:{
        items:1
      },
      
      550:{
        items:2
      },
      700:{
        items:4
      },
      1000:{
        items:6
      }
    }
  };

}

<!--Inner Banner-->
<div class="aboutbanner innerbanner">
    <div class="inner-breadcrumb">
          <div class="container">
            <div class="row align-items-center text-center">
                <div class="col-md-12 col-12 ">
                   <h2 class="breadcrumb-title">About Us</h2>
                    <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a [routerLink]="routes.home1">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">About us</li>
                        </ol>
                    </nav>							
                </div>
            </div>
          </div>		            
    </div>		            
</div>	
<!--/Inner Banner-->		

<!--About Content-->
<section class="about-content">
    <div class="container">
        <div class="about-listee">
            <div class="about-img">
                <img src="assets/img/about-img.jpg" class="img-fluid" alt="">
            </div>	
            <div class="about-info">
                <h4> <span>About</span> Listee</h4>  
                <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla fermentum malesuada pulvinar. Vestibulum laoreet rutrum semper. Vivamus malesuada, nisl in consectetur semper, mauris nulla aliquam risus, nec ultricies sapien elit sed ante. Aenean luctus felis in sem</p>
                <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla fermentum malesuada pulvinar. Vestibulum laoreet rutrum semper. Vivamus malesuada, </p>
            </div>
        </div>		
    </div>		
</section>
<!--/About Content-->

<!--How It Works-->
<section class="howitworks">
    <div class="container">
      <h3>How It Work</h3>
      <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla fermentum malesuada pulvinar. Vestibulum laoreet rutrum semper. Vivamus malesuada, nisl in consectetur semper, mauris nulla aliquam risus, nec ultricies sapien elit sed ante. Aenean luctus felis in sem consequat auctor. Nulla turpis enim, scelerisque sit amet consectetur vel, lacinia sed augue. Proin ultricies dui id ex fringilla porta.</p>
      <p>Morbi nisi justo, venenatis ac nibh at, bibendum mattis risus. Maecenas tincidunt, ligula sed congue tempus, magna augue cursus ipsum, in malesuada justo risus nec lorem. Nam augue augue, mollis nec condimentum euismod, lacinia ultricies leo.</p>
      <div class="row">
            <div class="col-lg-4 col-md-4 d-flex" *ngFor="let data of accountcreation">
                <div class="howitwork-info">
                    <h5>{{data. number}}</h5>
                    <h6>{{data.process}}</h6>
                    <p>{{data.details}}</p>
                </div>					  
            </div>
           					
          </div>
    </div>	
</section>
<!--/How It Works-->

<!--Popular Location-->
<div class="aboutpopular-locations">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-4">
                <div class="aboutlocation-details usa">
                <div class="aboutloc-img">
                    <img src="assets/img/locations/london-1.jpg" alt="">
                </div>
                <a [routerLink]="routes.listinggridsidebar">					   				    
                    <div class="aboutlocations-info">
                        <h3>London</h3>
                        <span>20+ Ads Posted</span>
                    </div> 
                </a> 						
                </div>				
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="aboutlocation-details usa">
                <div class="aboutloc-img">
                    <img src="assets/img/locations/usa-1.jpg" alt="">
                </div>
                <a [routerLink]="routes.listinggridsidebar">					   				    
                    <div class="aboutlocations-info">
                        <h3>USA</h3>
                        <span>15+ Ads Posted</span>
                    </div> 
                </a> 						
                </div>				
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="aboutlocation-details canada">
                    <div class="aboutloc-img">
                        <img src="assets/img/locations/canada-1.jpg" alt="">
                    </div>
                    <a [routerLink]="routes.listinggridsidebar">												    
                        <div class="aboutlocations-info">
                            <h3>Canada</h3>
                            <span>25+ Ads Posted</span>
                        </div> 
                    </a> 						
                </div>	
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="aboutlocation-details china">
                    <div class="aboutloc-img">
                        <img src="assets/img/locations/china-1.jpg" alt="">
                    </div>
                    <a [routerLink]="routes.listinggridsidebar">
                        <div class="aboutlocations-info">
                            <h3>China</h3>
                            <span>17+ Ads Posted</span>
                        </div> 
                    </a> 						
                </div>	 
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="aboutlocation-details uk">
                    <div class="aboutloc-img">
                        <img src="assets/img/locations/uk-1.jpg" alt="">
                    </div>
                    <a [routerLink]="routes.listinggridsidebar">
                        <div class="aboutlocations-info">
                            <h3>United Kingdom</h3>
                            <span>12+ Ads Posted</span>
                        </div> 
                    </a> 						
                </div>	 
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="aboutlocation-details australi-loc">
                    <div class="aboutloc-img">
                        <img src="assets/img/locations/australia-1.jpg" alt="">
                    </div>
                    <a [routerLink]="routes.listinggridsidebar">												    
                        <div class="aboutlocations-info">
                            <h3>Australia</h3>
                            <span>25+ Ads Posted</span>
                        </div> 
                    </a> 						
                </div>	 
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="aboutlocation-details france">
                    <div class="aboutloc-img">
                        <img src="assets/img/locations/france-1.jpg" alt="">
                    </div>
                    <a [routerLink]="routes.listinggridsidebar">
                        <div class="aboutlocations-info">
                            <h3>France</h3>
                            <span>14+ Ads Posted</span>
                        </div> 
                    </a> 						
                </div>	 
            </div>
        </div>
   </div>
</div>
<!--/Popular location-->

<!-- CTA Section -->
<section class="cta-section">
    <div class="container">
        <div class="row align-items-center">
             <div class="col-lg-7">
                  <div class="cta-content">
                      <h3>Earn Cash by <span>Selling</span> <br>
                      or Find Anything you desire							     
                      </h3>
                      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humo or randomised words which don't look even slightlys</p>
                      <div class="cta-btn">
                         <a [routerLink]="routes.addlisting" class="btn-primary postad-btn">Post Your Ads</a>
                         <a [routerLink]="routes.listinggridsidebar" class="browse-btn">Browse Ads</a>							  
                      </div>
                  </div>
             </div>
             <div class="col-lg-5">
                   <div class="cta-img">
                        <img src="assets/img/cta-img.png" class="img-fluid" alt="CTA">
                   </div>
             </div>
        </div>
    </div>
</section>		
<!-- /CTA Section -->

<!-- Client Testimonilas Section -->
<section class="testimonials-section">    
    <div class="row">
        <div class="col-lg-5">			
           <div class="testimonial-heading d-flex">
               <h4> Client <br> Testimonials</h4>
               <img src="assets/img/quotes.png" alt="quotes">
           </div>
        </div>
        <div class="col-lg-7">			
           <div class="rightimg"></div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="testimonials-slidersection">
            <div class="owl-nav mynav1"></div>
            <owl-carousel-o [options]="testimonialOwlOptions">
                <ng-container *ngFor="let slide of testimonial">
                    <ng-template carouselSlide>
            <div class="testi-slider">
                <div class="testimonial-info">
                    <div class="testimonialslider-heading d-flex">
                        <div class="testi-img">
                            <img [src]="slide.img" class="img-fluid" alt="testi-img">
                         </div>
                         <div class="testi-author">
                              <h6>{{slide.posting}}</h6>
                              <p>{{slide.position}}</p>
                         </div>
                        
                    </div>
                     <div class="testimonialslider-content">
                         <p>{{slide.para}}</p>
                    </div>
                </div>
            </div>
        </ng-template>
    </ng-container>

</owl-carousel-o>
            </div>
        </div>
    </div>		   
</section>		
<!-- /Client Testimonilas Section -->

<!-- Partners Section -->
<div class="partners-section">
    <div class="container">
        <p class="partners-heading">Over 5,26,000+ Sponsers being contact with us</p>	
        <owl-carousel-o [options]="universitiesCompaniesOwlOptions">
            <ng-container *ngFor="let slide of universitiesCompanies">
                <ng-template carouselSlide>
        
                <ul class="partnerslist d-flex">
           <li><a href="javascript:void(0);"><img class="img-fluid" [src]="slide.img" alt="partners"></a></li>
        </ul>
    </ng-template>
</ng-container>
</owl-carousel-o>
    </div>
</div>			
<!-- /Partners Section -->
