// listee-106/angular/src/app/featuremodule/userpages/profile/profile.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/core/helpers/routes/routes';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent {
public routes=routes;
public Toggledata = false;
public Toggle = false;



iconLogle() {
  this.Toggledata = !this.Toggledata;
 

}
icon(){
  this.Toggle = !this.Toggle;
}
}

<!-- Breadscrumb Section -->
<div class="breadcrumb-bar">
    <div class="container">
        <div class="row align-items-center text-center">
            <div class="col-md-12 col-12">
                <h2 class="breadcrumb-title">Profile</h2>
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a [routerLink]="routes.home1">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Profile</li>
                    </ol>
                </nav>							
            </div>
        </div>
    </div>
</div>
<!-- /Breadscrumb Section -->

<!-- Profile Content -->
<div class="dashboard-content">		
    <div class="container">
        <div class="">			        
            <ul class="dashborad-menus">
                <li>
                    <a [routerLink]="routes.dashboard">
                        <i class="feather-grid"></i> <span>Dashboard</span>
                    </a>
                </li>
                <li  class="active">
                    <a [routerLink]="routes.profile">
                        <i class="fa-solid fa-user"></i> <span>Profile</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.mylisting">
                        <i class="feather-list"></i> <span>My Listing</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.bookmarks">
                        <i class="fas fa-solid fa-heart"></i> <span>Bookmarks</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.messages">
                        <i class="fa-solid fa-comment-dots"></i> <span>Messages</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.reviews">
                        <i class="fas fa-solid fa-star"></i> <span>Reviews</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.login">
                        <i class="fas fa-light fa-circle-arrow-left"></i> <span>Logout</span>
                    </a>
                </li>
            </ul>											
        </div>
        <div class="profile-content">
             <div class="row dashboard-info">
                <div class="col-lg-9">
                    <div class="card dash-cards">
                        <div class="card-header">
                            <h4>Profile Details</h4>																
                        </div>
                        <div class="card-body">
                            <div class="profile-photo">
                                <div class="profile-img">
                                    <div class="settings-upload-img">
                                         <img src="assets/img/profile-img.jpg" alt="profile">
                                    </div>										    
                                     <div class="settings-upload-btn">											    
                                        <input type="file" accept="image/*" name="image" class="hide-input image-upload" id="file">
                                        <label for="file" class="file-upload">Upload New photo</label>												
                                     </div>	
                                     <span>Max file size: 10 MB</span>
                                </div>                                        									
                                <a href="javascript:void(0)" class="profile-img-del"><i class="feather-trash-2"></i></a>										
                            </div>
                            <div class="profile-form">
                                 <form>
                                    <div class="form-group">
                                        <label class="col-form-label">Your Full Name</label>
                                        <div class="pass-group group-img">
                                            <span class="lock-icon"><i class="feather-user"></i></span>
                                            <input type="text" class="form-control" value="John Doe">													
                                        </div>
                                    </div> 
                                    <div class="row">
                                         <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <label class="col-form-label">Phone Number</label>
                                                <div class="pass-group group-img">
                                                    <span class="lock-icon"><i class="feather-phone-call"></i></span>
                                                    <input type="tel" class="form-control" value="+44 215346 1223">													
                                                </div>
                                            </div>
                                         </div>
                                         <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <label class="col-form-label">Email Address</label>
                                                <div class="group-img">
                                                    <i class="feather-mail"></i>
                                                    <input type="text" class="form-control" value="johndoe@email.com">
                                                </div>
                                            </div>
                                         </div>											
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Notes</label>
                                        <div class="pass-group group-img">
                                            <textarea rows="4" class="form-control">Mauris vestibulum lorem a condimentum vulputate. Integer vitae turpis turpis. Cras at tincidunt urna. Aenean leo justo, congue et felis a, elementum rutrum felis. Fusce rutrum ipsum eu pretium faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean leo justo, congue et felis a.  Aenean leo justo, congue et felis a.	</textarea>												
                                        </div>
                                    </div>
                                    <div class="row socialmedia-info">
                                         <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <label class="col-form-label">Facebook</label>
                                                <div class="pass-group group-img">
                                                    <span class="lock-icon"><i class="fab fa-facebook-f"></i></span>
                                                    <input type="text" class="form-control" value="https://www.facebook.com/">												
                                                </div>
                                            </div>
                                         </div>
                                         <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <label class="col-form-label">Twitter</label>
                                                <div class="pass-group group-img">
                                                    <span class="lock-icon"><i class="fab fa-twitter"></i></span>
                                                    <input type="text" class="form-control" value="https://twitter.com/">												
                                                </div>
                                            </div>
                                         </div>											
                                    </div>
                                    <div class="row socialmedia-info">
                                         <div class="col-lg-6 col-md-6">
                                            <div class="form-group formlast-input">
                                                <label class="col-form-label">Google+</label>
                                                <div class="pass-group group-img">
                                                    <span class="lock-icon"><i class="fa-brands fa-google-plus-g"></i></span>
                                                    <input type="text" class="form-control" value="https://www.google.com/">												
                                                </div>
                                            </div>
                                         </div>
                                         <div class="col-lg-6 col-md-6">
                                            <div class="form-group formlast-input">
                                                <label class="col-form-label">Instagram</label>
                                                <div class="pass-group group-img">
                                                    <span class="lock-icon"><i class="fab fa-instagram"></i></span>
                                                    <input type="text" class="form-control" value="https://www.instagram.com/">												
                                                </div>
                                            </div>
                                         </div>											
                                    </div>										 
                                 </form>
                            </div> 
                        </div>								
                    </div>	
                </div>
                <div class="col-lg-3">
                    <div class="profile-sidebar">
                        <div class="card">
                            <div class="card-header">
                                <h4>Change Password</h4>
                            </div>	
                            <div class="card-body">
                               <form>
                                    <div class="form-group">
                                        <label class="col-form-label">Current Password</label>
                                        <div class="pass-group group-img">
                                            <span class="lock-icon"><i class="feather-lock"></i></span>
                                            <input type="password" class="form-control pass-input" placeholder="Password">													
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">New Password</label>
                                        <div class="pass-group group-img">
                                            <span class="lock-icon"><i class="feather-lock"></i></span>
                                            <input type="password" class="form-control pass-input" value="..............">
                                            
                                            <span  [ngClass]="Toggledata == true ? 'toggle-password feather-eye' : 'toggle-password feather-eye-off'"  (click)="iconLogle()"></span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Confirm New Password</label>
                                        <div class="pass-group group-img">
                                            <span class="lock-icon"><i class="feather-lock"></i></span>
                                            <input type="password" class="form-control pass-input" value="..............">
                                            <span [ngClass]="Toggle == true ? 'toggle-password feather-eye' : 'toggle-password feather-eye-off'" (click)="icon()"></span>
                                        </div>
                                    </div>	
                                    <button class="btn btn-primary" type="submit"> Change Password</button>											
                               </form>								
                            </div>  									
                        </div>							
                    </div>
                </div>							
             </div>				
        </div>
    </div>		
</div>		
<!-- /Profile Content -->

// listee-106/reactjs/src/components/userPages/profile.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import { profile_img } from "../imagepath";
import Header from "../home/header";
import Footer from "../home/footer/Footer";
import UserHeader from "./Userheader";



const Profile = () => {
    const [passwordType, setPasswordType] = useState("password");
  const [passwordInput, setPasswordInput] = useState("");
  const handlePasswordChange =(evnt)=>{
    setPasswordInput(evnt.target.value);
}

const togglePassword =()=>{
  if(passwordType==="password")
  {
   setPasswordType("text")
   return;
  }
  setPasswordType("password")
}
    return (
        <>
        <UserHeader/>
            {/* Breadscrumb Section */}
            <div className="breadcrumb-bar">
                <div className="container">
                    <div className="row align-items-center text-center">
                        <div className="col-md-12 col-12">
                            <h2 className="breadcrumb-title">Profile</h2>
                            <nav aria-label="breadcrumb" className="page-breadcrumb">
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <Link to="/index">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active" aria-current="page">
                                        Profile
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadscrumb Section */}
            {/* Profile Content */}
            <div className="dashboard-content">
                <div className="container">
                    <div className="">
                        <ul className="dashborad-menus">
                            <li>
                                <Link to="/dashboard">
                                    <i className="feather-grid" /> <span>Dashboard</span>
                                </Link>
                            </li>
                            <li className="active">
                                <Link to="/profile">
                                    <i className="fa-solid fa-user" /> <span>Profile</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/my-listing">
                                    <i className="feather-list" /> <span>My Listing</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/bookmarks">
                                    <i className="fas fa-solid fa-heart" /> <span>Bookmarks</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/messages">
                                    <i className="fa-solid fa-comment-dots" /> <span>Messages</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/reviews">
                                    <i className="fas fa-solid fa-star" /> <span>Reviews</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/login">
                                    <i className="fas fa-light fa-circle-arrow-left" />{" "}
                                    <span>Logout</span>
                                </Link>
                            </li>
                        </ul>
                    </div>
                    <div className="profile-content">
                        <div className="row dashboard-info">
                            <div className="col-lg-9">
                                <div className="card dash-cards">
                                    <div className="card-header">
                                        <h4>Profile Details</h4>
                                    </div>
                                    <div className="card-body">
                                        <div className="profile-photo">
                                            <div className="profile-img">
                                                <div className="settings-upload-img">
                                                    <img src={profile_img} alt="profile" />
                                                </div>
                                                <div className="settings-upload-btn">
                                                    <input
                                                        type="file"
                                                        accept="image/*"
                                                        name="image"
                                                        className="hide-input image-upload"
                                                        id="file"
                                                    />
                                                    <label htmlFor="file" className="file-upload">
                                                        Upload New photo
                                                    </label>
                                                </div>
                                                <span>Max file size: 10 MB</span>
                                            </div>
                                            <Link to="#" className="profile-img-del">
                                                <i className="feather-trash-2" />
                                            </Link>
                                        </div>
                                        <div className="profile-form">
                                            <form>
                                                <div className="form-group">
                                                    <label className="col-form-label">Your Full Name</label>
                                                    <div className="pass-group group-img">
                                                        <span className="lock-icon">
                                                            <i className="feather-user" />
                                                        </span>
                                                        <input
                                                            type="text"
                                                            className="form-control"
                                                            defaultValue="John Doe"
                                                        />
                                                    </div>
                                                </div>
                                                <div className="row">
                                                    <div className="col-lg-6 col-md-6">
                                                        <div className="form-group">
                                                            <label className="col-form-label">Phone Number</label>
                                                            <div className="pass-group group-img">
                                                                <span className="lock-icon">
                                                                    <i className="feather-phone-call" />
                                                                </span>
                                                                <input
                                                                    type="tel"
                                                                    className="form-control"
                                                                    defaultValue="+44 215346 1223"
                                                                />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="col-lg-6 col-md-6">
                                                        <div className="form-group">
                                                            <label className="col-form-label">
                                                                Email Address
                                                            </label>
                                                            <div className="group-img">
                                                                <i className="feather-mail" />
                                                                <input
                                                                    type="text"
                                                                    className="form-control"
                                                                    defaultValue="johndoe@email.com"
                                                                />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="form-group">
                                                    <label className="col-form-label">Notes</label>
                                                    <div className="pass-group group-img">
                                                        <textarea
                                                            rows={4}
                                                            className="form-control"
                                                            defaultValue={
                                                                "Mauris vestibulum lorem a condimentum vulputate. Integer vitae turpis turpis. Cras at tincidunt urna. Aenean leo justo, congue et felis a, elementum rutrum felis. Fusce rutrum ipsum eu pretium faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean leo justo, congue et felis a.  Aenean leo justo, congue et felis a.\t"
                                                            }
                                                        />
                                                    </div>
                                                </div>
                                                <div className="row socialmedia-info">
                                                    <div className="col-lg-6 col-md-6">
                                                        <div className="form-group">
                                                            <label className="col-form-label">Facebook</label>
                                                            <div className="pass-group group-img">
                                                                <span className="lock-icon">
                                                                    <i className="fab fa-facebook-f" />
                                                                </span>
                                                                <input
                                                                    type="text"
                                                                    className="form-control"
                                                                    defaultValue="https://www.facebook.com/"
                                                                />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="col-lg-6 col-md-6">
                                                        <div className="form-group">
                                                            <label className="col-form-label">Twitter</label>
                                                            <div className="pass-group group-img">
                                                                <span className="lock-icon">
                                                                    <i className="fab fa-twitter" />
                                                                </span>
                                                                <input
                                                                    type="text"
                                                                    className="form-control"
                                                                    defaultValue="https://twitter.com/"
                                                                />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="row socialmedia-info">
                                                    <div className="col-lg-6 col-md-6">
                                                        <div className="form-group formlast-input">
                                                            <label className="col-form-label">Google+</label>
                                                            <div className="pass-group group-img">
                                                                <span className="lock-icon">
                                                                    <i className="fa-brands fa-google-plus-g" />
                                                                </span>
                                                                <input
                                                                    type="text"
                                                                    className="form-control"
                                                                    defaultValue="https://www.google.com/"
                                                                />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="col-lg-6 col-md-6">
                                                        <div className="form-group formlast-input">
                                                            <label className="col-form-label">Instagram</label>
                                                            <div className="pass-group group-img">
                                                                <span className="lock-icon">
                                                                    <i className="fab fa-instagram" />
                                                                </span>
                                                                <input
                                                                    type="text"
                                                                    className="form-control"
                                                                    defaultValue="https://www.instagram.com/"
                                                                />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-3">
                                <div className="profile-sidebar">
                                    <div className="card">
                                        <div className="card-header">
                                            <h4>Change Password</h4>
                                        </div>
                                        <div className="card-body">
                                            <form>
                                                <div className="form-group">
                                                    <label className="col-form-label">Current Password</label>
                                                    <div className="pass-group group-img">
                                                        <span className="lock-icon">
                                                            <i className="feather-lock" />
                                                        </span>
                                                        <input
                                                            type="password"
                                                            className="form-control pass-input"
                                                            placeholder="Password"
                                                        />
                                                    </div>
                                                </div>
                                                <div className="form-group">
                                                    <label className="col-form-label">New Password</label>
                                                    <div className="pass-group group-img">
                                                        <span className="lock-icon">
                                                            <i className="feather-lock" />
                                                        </span>
                                                        <input
                                                            type={passwordType}
                                                            className="form-control pass-input"
                                                            defaultValue=".............."
                                                            onChange={handlePasswordChange}
                                                            
                                                        />
                                                        <span className={`toggle-password  ${ passwordType==="password"? "feather-eye":"feather-eye-off" } `} onClick={togglePassword} />
                                                    </div>
                                                </div>
                                                <div className="form-group">
                                                    <label className="col-form-label">
                                                        Confirm New Password
                                                    </label>
                                                    <div className="pass-group group-img">
                                                        <span className="lock-icon">
                                                            <i className="feather-lock" />
                                                        </span>
                                                        <input
                                                            type={passwordType}
                                                            className="form-control pass-input"
                                                            defaultValue=".............."
                                                            onChange={handlePasswordChange}
                                                            
                                                        />
                                                        <span className={`toggle-password  ${ passwordType==="password"? "feather-eye":"feather-eye-off" } `} onClick={togglePassword} />
                                                    </div>
                                                </div>
                                                <button className="btn btn-primary" type="submit">
                                                    {" "}
                                                    Change Password
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Profile Content */}
            <Footer/>
        </>

    );
}
export default Profile;
