// listee-106/reactjs/src/components/forgotPassword/index.jsx
import React from "react";
import Header from "../home/header";
import Footer from "../home/footer/Footer";
import { Link } from "react-router-dom";




const ForgotPassword = () => {
    return (
        <>
            <Header />
            {/* Breadscrumb Section */}
            <div className="breadcrumb-bar">
                <div className="container">
                    <div className="row align-items-center text-center">
                        <div className="col-md-12 col-12">
                            <h2 className="breadcrumb-title">Forgot Password</h2>
                            <nav aria-label="breadcrumb" className="page-breadcrumb">
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <Link to="index">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active" aria-current="page">
                                        Forgot Password
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadscrumb Section */}
            {/* Login Section */}
            <div className="login-content">
                <div className="container">
                    <div className="row">
                        <div className="col-md-6 col-lg-5 mx-auto">
                            <div className="login-wrap password-form">
                                <div className="login-header">
                                    <h3>Forgot Password</h3>
                                    <p>
                                        Enter your email and we will send you a link to reset your
                                        password.
                                    </p>
                                </div>
                                {/* Login Form */}
                                <form action="login">
                                    <div className="form-group group-img">
                                        <div className="group-img">
                                            <i className="feather-mail" />
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="Email Address"
                                            />
                                        </div>
                                    </div>
                                    <button className="btn btn-primary w-100 login-btn" type="submit">
                                        Submit
                                    </button>
                                </form>
                                <Link to="index" className="back-home">
                                    <i className="fas fa-regular fa-arrow-left me-1" /> Back to Home
                                </Link>
                                {/* /Login Form */}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Login Section */}
            <Footer />
        </>

    );
}
export default ForgotPassword;

// listee-106/angular/src/app/auth/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { routes } from 'src/app/core/helpers/routes/routes';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.css']
})
export class ForgotPasswordComponent {
  public routes = routes;

  constructor(public router: Router){

  }
  direction(){
    this.router.navigate([routes.login])
  }
}

<!-- Breadscrumb Section -->
<div class="breadcrumb-bar">
    <div class="container">
        <div class="row align-items-center text-center">
            <div class="col-md-12 col-12">
                <h2 class="breadcrumb-title">Forgot Password</h2>
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a [routerLink]="routes.home">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Forgot Password</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- /Breadscrumb Section -->

<!-- Login Section -->
<div class="login-content">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-5 mx-auto">
                <div class="login-wrap password-form">

                    <div class="login-header">
                        <h3>Forgot Password</h3>
                        <p>Enter your email and we will send you a link to reset your password.</p>
                    </div>

                    <!-- Login Form -->
                    <form >
                        <div class="form-group group-img">
                            <div class="group-img">
                                <i class="feather-mail"></i>
                                <input type="text" class="form-control" placeholder="Email Address">
                            </div>
                        </div>
                        <button (click)="direction()" class="btn btn-primary w-100 login-btn" type="submit">Submit</button>
                    </form>
                    <a [routerLink]="routes.home1" class="back-home"><i class="fas fa-regular fa-arrow-left me-1"></i> Back to Home</a>
                    <!-- /Login Form -->

                </div>
            </div>
        </div>

    </div>
</div>
<!-- /Login Section -->
