// listee-106/angular/src/app/featuremodule/pages/pricing/pricing.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/core/helpers/routes/routes';
import { DataService } from 'src/app/service/data.service';

@Component({
  selector: 'app-pricing',
  templateUrl: './pricing.component.html',
  styleUrls: ['./pricing.component.css']
})
export class PricingComponent {
  public routes=routes;
  public pricing :any =[];
  constructor (private dataservice:DataService){
    this.pricing=this.dataservice.pricingList
  }


}

<!-- Breadscrumb Section -->
<div class="breadcrumb-bar">
    <div class="container">
        <div class="row align-items-center text-center">
            <div class="col-md-12 col-12">
                <h2 class="breadcrumb-title">Pricing Plan</h2>
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a [routerLink]="routes.home1">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Pricing Plan</li>
                    </ol>
                </nav>							
            </div>
        </div>
    </div>
</div>
<!-- /Breadscrumb Section -->
         
<!-- Pricing Plan Section -->
<section class="pricingplan-section pricing-page">
         <div class="section-heading">
                <div class="container">				
                     <div class="row text-center">
                            <h2>Our Pricing <span>Pla</span>n</h2>
                            <p>checkout these latest cool ads from our members</p>
                     </div>									 
                </div>	 
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 d-flex col-md-6" *ngFor="let slide of pricing">
                    <div class="price-card flex-fill">
                        <div class="price-head">
                            <div class="price-level">
                                <h6>{{slide.title}}</h6>
                            </div>
                            <h4>{{slide. pricedate}} <span>{{slide.pricemonth}}</span></h4>								
                        </div>	
                        <div class="price-body">
                            <p>{{slide.pricebody}}</p>
                            <ul>
                                <li class="active">{{slide.pricebodyList}}</li>
                                <li class="active">{{slide.pricebodyList1}}</li>
                                <li class="active">{{slide.pricebodyList2}}</li>
                                <li class="inactive">{{slide.pricebodyList3}}</li>
                                <li class="inactive">{{slide.pricebodyList4}}</li>
                            </ul>
                            <div>
                                <a [routerLink]="routes.login" class="btn viewdetails-btn">View details</a>
                            </div>							
                        </div>							
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- /Pricing Plan Section -->

// listee-106/reactjs/src/components/pages/about/pricing/index.jsx
import React from "react";
import Header from "../../../home/header";
import Footer from "../../../home/footer/Footer";
import { Link, useLocation } from "react-router-dom";




const Pricing = () => {
    const parms=useLocation().pathname
    return (
        <>
            <Header parms={parms}/>
            {/* Breadscrumb Section */}
            <div className="breadcrumb-bar">
                <div className="container">
                    <div className="row align-items-center text-center">
                        <div className="col-md-12 col-12">
                            <h2 className="breadcrumb-title">Pricing Plan</h2>
                            <nav aria-label="breadcrumb" className="page-breadcrumb">
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <Link to="/index">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active" aria-current="page">
                                        Pricing Plan
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadscrumb Section */}
            {/* Pricing Plan Section */}
            <section className="pricingplan-section pricing-page">
                <div className="section-heading">
                    <div className="container">
                        <div className="row text-center">
                            <h2>
                                Our Pricing <span>Pla</span>n
                            </h2>
                            <p>checkout these latest cool ads from our members</p>
                        </div>
                    </div>
                </div>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-3 d-flex col-md-6">
                            <div className="price-card flex-fill">
                                <div className="price-head">
                                    <div className="price-level">
                                        <h6>Intro</h6>
                                    </div>
                                    <h4>
                                        $10 <span>/ month</span>
                                    </h4>
                                </div>
                                <div className="price-body">
                                    <p>For most business that want to optimize web queries</p>
                                    <ul>
                                        <li className="active">Basic listing submission</li>
                                        <li className="active">One Listing</li>
                                        <li className="active">30 days Availabilty</li>
                                        <li className="inactive">Limited Support</li>
                                        <li className="inactive">Edit your listing</li>
                                    </ul>
                                    <div>
                                        <Link to="/login" className="btn viewdetails-btn">
                                            View details
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-3 d-flex col-md-6">
                            <div className="price-card flex-fill">
                                <div className="price-head">
                                    <div className="price-level">
                                        <h6>Basic</h6>
                                    </div>
                                    <h4>
                                        $25 <span>/ month</span>
                                    </h4>
                                </div>
                                <div className="price-body">
                                    <p>For most business that want to optimize web queries</p>
                                    <ul>
                                        <li className="active">Basic listing submission</li>
                                        <li className="active">One Listing</li>
                                        <li className="active">30 days Availabilty</li>
                                        <li className="inactive">Limited Support</li>
                                        <li className="inactive">Edit your listing</li>
                                    </ul>
                                    <div>
                                        <Link to="/login" className="btn viewdetails-btn">
                                            View details
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-3 d-flex col-md-6">
                            <div className="price-card flex-fill">
                                <div className="price-head">
                                    <div className="price-level">
                                        <h6>Popular</h6>
                                    </div>
                                    <h4>
                                        $50 <span>/ month</span>
                                    </h4>
                                </div>
                                <div className="price-body">
                                    <p>For most business that want to optimize web queries</p>
                                    <ul>
                                        <li className="active">Basic listing submission</li>
                                        <li className="active">One Listing</li>
                                        <li className="active">30 days Availabilty</li>
                                        <li className="inactive">Limited Support</li>
                                        <li className="inactive">Edit your listing</li>
                                    </ul>
                                    <div>
                                        <Link to="/login" className="btn viewdetails-btn">
                                            View details
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-3 d-flex col-md-6">
                            <div className="price-card flex-fill">
                                <div className="price-head">
                                    <div className="price-level">
                                        <h6>Enterprise</h6>
                                    </div>
                                    <h4>
                                        $100 <span>/ month</span>
                                    </h4>
                                </div>
                                <div className="price-body">
                                    <p>For most business that want to optimize web queries</p>
                                    <ul>
                                        <li className="active">Basic listing submission</li>
                                        <li className="active">One Listing</li>
                                        <li className="active">30 days Availabilty</li>
                                        <li className="inactive">Limited Support</li>
                                        <li className="inactive">Edit your listing</li>
                                    </ul>
                                    <div>
                                        <Link to="/login" className="btn viewdetails-btn">
                                            View details
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* /Pricing Plan Section */}

            <Footer/>
        </>

    );
}
export default Pricing;
