// listee-106/reactjs/src/components/userPages/mylisting/index.jsx
import React from "react";

import Mylistings from "../../json/Mylisting"
import { Table } from "antd";
import { Link, useLocation } from "react-router-dom";
import Footer from "../../home/footer/Footer";
import UserHeader from "../Userheader";


const MyListe = () => {
    const data = Mylistings.Mylistings;
    const dataSource = {
        data,

    };

    const columns = [
        {
            title: 'Image',
            dataIndex: 'image',
            render: (text, record, data) => (


                <div className="listingtable-img">
                    {" "}
                    <Link to="/service-details">
                        <img
                            className="img-fluid avatar-img"
                            src={text}
                            alt=""
                        />
                    </Link>
                </div>

            ),
            sorter: (a, b) => { a.image.length - b.image.length }
        },
        {
            title: 'Details',
            dataIndex: 'content',
            render: (text, record, data) => (
                <>
                    <h6>
                        <Link to="/service-details">
                            {text}
                        </Link>
                    </h6>
                    <div className="listingtable-rate">
                        <Link to="#" className="cat-icon">
                            <i className="fa-regular fa-circle-stop" />{" "}
                            Electronics
                        </Link>{" "}
                        <span className="discount-amt">$350000.00</span>
                        <span className="fixed-amt">$40000</span>
                    </div>
                    <p>Mauris vestibulum lorem a condimentum vulputate.</p>
                </>
            ),
            sorter: (a, b) => { a.content.length - b.content.length }
        },
        {
            title: 'Status',
            dataIndex: 'status',
            render: (text, record, data) => (
                <span className={record.bg}>{text}</span>
            ),
            sorter: (a, b) => { a.status.length - b.status.length }
        },
        {
            title: 'Views',
            dataIndex: 'numbers',
            render: (text, record, data) => (
                <span>{text}</span>
            ),
            sorter: (a, b) => { a.numbers.length - b.numbers.length }
        },
        {
            title: 'Action',
            dataIndex: 'class',
            render: (text, record, data) => (
                <div className={text}>
                    <Link
                        to="#"
                        className="action-btn btn-view"
                    >
                        <i className="feather-eye" />
                    </Link>
                    <Link
                        to="#"
                        className="action-btn btn-edit"
                    >
                        <i className="feather-edit-3" />
                    </Link>
                    <Link
                        to="#"
                        className="action-btn btn-trash"
                    >
                        <i className="feather-trash-2" />
                    </Link>
                </div>
            ),
            sorter: (a, b) => { a.class.length - b.class.length }
        },


    ]
    const parms=useLocation().pathname
    return (
        <>
            <UserHeader parms={parms}/>
            {/* Breadscrumb Section */}
            <div className="breadcrumb-bar">
                <div className="container">
                    <div className="row align-items-center text-center">
                        <div className="col-md-12 col-12">
                            <h2 className="breadcrumb-title">My Listing</h2>
                            <nav aria-label="breadcrumb" className="page-breadcrumb">
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <Link to="/index">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active" aria-current="page">
                                        My Listing
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadscrumb Section */}
            {/* Dashboard Content */}
            <div className="dashboard-content">
                <div className="container">
                    <div className="">
                        <ul className="dashborad-menus">
                            <li>
                                <Link to="/dashboard">
                                    <i className="feather-grid" /> <span>Dashboard</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/profile">
                                    <i className="fa-solid fa-user" /> <span>Profile</span>
                                </Link>
                            </li>
                            <li className="active">
                                <Link to="/my-listing">
                                    <i className="feather-list" /> <span>My Listing</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/bookmarks">
                                    <i className="fas fa-solid fa-heart" /> <span>Bookmarks</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/messages">
                                    <i className="fa-solid fa-comment-dots" /> <span>Messages</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/reviews">
                                    <i className="fas fa-solid fa-star" /> <span>Reviews</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/login">
                                    <i className="fas fa-light fa-circle-arrow-left" />{" "}
                                    <span>Logout</span>
                                </Link>
                            </li>
                        </ul>
                    </div>
                    <div className="dash-listingcontent dashboard-info">
                        <div className="dash-cards card">
                            <div className="card-header">
                                <h4>My Listings</h4>
                                <Link
                                    className="nav-link header-login add-listing"
                                    to="/add-listing"
                                >
                                    <i className="fa-solid fa-plus" /> Add Listing
                                </Link>
                            </div>
                            <div className="card-body">
                                <div className="listing-search">
                                    <div className="filter-content form-group">
                                        <div className="group-img">
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="Search..."
                                            />
                                            <i className="feather-search" />
                                        </div>
                                    </div>
                                    <div className="sorting-div">
                                        <div className="sortbyset">
                                            <span className="sortbytitle">Sort by</span>
                                            <div className="sorting-select">
                                                <select className="form-control select">
                                                    <option>Newest</option>
                                                    <option>Newest</option>
                                                    <option>Oldest</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="table-responsive">
                                    
                                        <Table
                                            className="listing-table datatable"
                                            columns={columns}
                                            // bordered
                                            dataSource={data}
                                            rowKey={(record) => record.id}
                                            showSizeChanger={true}
                                            


                                        />
                                    
                                </div>
                                <div className="blog-pagination">
                                    <nav>
                                        <ul className="pagination">
                                            <li className="page-item previtem">
                                                <Link className="page-link" to="#">
                                                    <i className="fas fa-regular fa-arrow-left" /> Prev
                                                </Link>
                                            </li>
                                            <li className="justify-content-center pagination-center">
                                                <div className="pagelink">
                                                    <ul>
                                                        <li className="page-item">
                                                            <Link className="page-link" to="#">
                                                                1
                                                            </Link>
                                                        </li>
                                                        <li className="page-item active">
                                                            <Link className="page-link" to="#">
                                                                2 <span className="visually-hidden">(current)</span>
                                                            </Link>
                                                        </li>
                                                        <li className="page-item">
                                                            <Link className="page-link" to="#">
                                                                3
                                                            </Link>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </li>
                                            <li className="page-item nextlink">
                                                <Link className="page-link" to="#">
                                                    Next <i className="fas fa-regular fa-arrow-right" />
                                                </Link>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Dashboard Content */}
            <Footer/>
        </>

    );
}
export default MyListe;

// listee-106/angular/src/app/featuremodule/userpages/my-listing/my-listing.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { routes } from 'src/app/core/helpers/routes/routes';
import { DataService } from 'src/app/service/data.service';

@Component({
  selector: 'app-my-listing',
  templateUrl: './my-listing.component.html',
  styleUrls: ['./my-listing.component.css']
})
export class MyListingComponent {
  public routes=routes;
  public electronics:any=[]

  constructor(private DataService:DataService){
    this.electronics=this.DataService.electronicsList
  }
  sortData(sort: Sort) {
    const data = this.electronics.slice();

    if (!sort.active || sort.direction === '') {
      this.electronics = data;
    } else {
      this.electronics = data.sort((a: any, b: any) => {
        const aValue = (a as any)[sort.active];
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }


}

<!-- Breadscrumb Section -->
<div class="breadcrumb-bar">
    <div class="container">
        <div class="row align-items-center text-center">
            <div class="col-md-12 col-12">
                <h2 class="breadcrumb-title">My Listing</h2>
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a [routerLink]="routes.home1">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">My Listing</li>
                    </ol>
                </nav>							
            </div>
        </div>
    </div>
</div>
<!-- /Breadscrumb Section -->
<!-- Dashboard Content -->
<div class="dashboard-content">		
    <div class="container">
        <div class="">			        
            <ul class="dashborad-menus">
                <li>
                    <a [routerLink]="routes.dashboard">
                        <i class="feather-grid"></i> <span>Dashboard</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.profile">
                        <i class="fa-solid fa-user"></i> <span>Profile</span>
                    </a>
                </li>
                <li  class="active">
                    <a [routerLink]="routes.mylisting">
                        <i class="feather-list"></i> <span>My Listing</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.bookmarks">
                        <i class="fas fa-solid fa-heart"></i> <span>Bookmarks</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.messages">
                        <i class="fa-solid fa-comment-dots"></i> <span>Messages</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.reviews">
                        <i class="fas fa-solid fa-star"></i> <span>Reviews</span>
                    </a>
                </li>
                <li>
                    <a [routerLink]="routes.login">
                        <i class="fas fa-light fa-circle-arrow-left"></i> <span>Logout</span>
                    </a>
                </li>
            </ul>																
        </div>
        <div class="dash-listingcontent dashboard-info">
            <div class="dash-cards card">
                <div class="card-header">
                    <h4>My Listings</h4>
                    <a class="nav-link header-login add-listing" [routerLink]="routes.addlisting"><i class="fa-solid fa-plus"></i> Add Listing</a>									
                </div>
                <div class="card-body">
                    <div class="listing-search">
                        <div class="filter-content form-group">
                            <div class="group-img">
                              <input type="text" class="form-control" placeholder="Search...">
                              <i class="feather-search"></i>
                            </div>
                        </div>
                        <div class="sorting-div">
                             <div class="sortbyset">
                                <span class="sortbytitle">Sort by</span>
                                <div class="sorting-select">
                                     <select class="form-control select">
                                        <option>Newest</option>
                                        <option>Newest</option>
                                        <option>Oldest</option>
                                    </select>
                                </div>
                            </div>						
                        </div>																
                    </div>
                    <div class="table-responsive">
                        <table  matSort (matSortChange)="sortData($event)" class="listing-table datatable" id="listdata-table"  >
                           <thead>								    
                            <tr>
                                <th mat-sort-header="img"class="no-sort" >Image</th>										 
                                <th mat-sort-header="details"class="no-sort">Details</th>										 
                                <th mat-sort-header="status">Status</th>										 
                                <th mat-sort-header="view">Views</th>										 
                                <th mat-sort-header="Action">Action</th>										 
                             </tr>	
                             </thead>
                             <tbody>									 
                             <tr *ngFor="let data of electronics">
                                 <td>
                                    <div class="listingtable-img"> <a [routerLink]="routes.servicedetails"><img class="img-fluid avatar-img" [src]="data.img" alt=""></a></div>
                                 </td>
                                 <td>
                                     <h6><a [routerLink]="routes.servicedetails">{{data. details}}</a></h6>
                                     <div class="listingtable-rate"><a href="javascript:void(0)" class="cat-icon"><i class="fa-regular fa-circle-stop"></i> {{data.select}}</a> <span class="discount-amt">{{data.oldamount}}</span><span class="fixed-amt">{{data.newamount}}</span></div>
                                     <p>{{data.description}}</p>
                                 </td>
                                 <td><span [ngClass]="{'unpublish': data.status === 'Un Published' }"
                                    class="status-text">{{data.status}}</span></td>
                                 <td><span class="views-count">{{data.view}}</span></td>
                                 <td>
                                    <div class="action">
                                        <a href="javascript:void(0)" class="action-btn btn-view"><i class="feather-eye"></i></a>
                                        <a href="javascript:void(0)" class="action-btn btn-edit"><i class="feather-edit-3"></i></a>
                                        <a href="javascript:void(0)" class="action-btn btn-trash"><i class="feather-trash-2"></i></a>
                                    
                                    </div>
                                 </td>
                             </tr> 
                          
                             </tbody>									 
                        </table>				
                    </div>
                    <div class="blog-pagination">
                        <nav>
                            <ul class="pagination">
                                <li class="page-item previtem">
                                    <a class="page-link" href="javascript:void(0)"><i class="fas fa-regular fa-arrow-left"></i> Prev</a>
                                </li>
                                <li class="justify-content-center pagination-center"> 
                                    <div class="pagelink">
                                        <ul>
                                            <li class="page-item">
                                                <a class="page-link" href="javascript:void(0)">1</a>
                                            </li>
                                            <li class="page-item active">
                                                <a class="page-link" href="javascript:void(0)">2 <span class="visually-hidden">(current)</span></a>
                                            </li>
                                            <li class="page-item">
                                                <a class="page-link" href="javascript:void(0)">3</a>
                                           </li>
                                       </ul>
                                    </div>													
                                </li>													
                                <li class="page-item nextlink">
                                    <a class="page-link" href="javascript:void(0)">Next <i class="fas fa-regular fa-arrow-right"></i></a>
                                </li>
                            </ul>
                        </nav>
                    </div>										
                </div>							
            </div>                  							
        </div>							
    </div>				
</div>			
<!-- /Dashboard Content -->
