// listee-106/vuejs/src/views/pages/Error/error404/Error404.vue
<template>
    <div class="mainwrapper error-page">
	   	<div class="content">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 mx-auto">
						<div class="error-wrap">
						
							<div class="error-logo">
								<router-link to="index"><img class="img-fluid" src="../../../../assets/img/logo.svg" alt="img"></router-link>
							</div>
							<h2>Something went wrong</h2>
							<div class="error-img">
								<img class="img-fluid" src="../../../../assets/img/404-error.jpg" alt="img">
							</div>
							<router-link to="/" class="btn btn-primary rounded-pill">Back to Home</router-link>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

// listee-106/angular/src/app/error/error404/error404.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { routes } from 'src/app/core/helpers/routes/routes';

@Component({
  selector: 'app-error404',
  templateUrl: './error404.component.html',
  styleUrls: ['./error404.component.css']
})
export class Error404Component {
  public routes = routes;
  constructor(public router: Router){

  }

}

<div class="mainwrapper error-page">
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mx-auto">
          <div class="error-wrap">
            <div class="error-logo">
              <a [routerLink]="routes.home1"
                ><img class="img-fluid" src="assets/img/logo.svg" alt="img"
              /></a>
            </div>
            <h2>Something went wrong</h2>
            <div class="error-img">
              <img class="img-fluid" src="assets/img/404-error.jpg" alt="img" />
            </div>
            <a [routerLink]="routes.home1" class="btn btn-primary rounded-pill"
              >Back to Home</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
