// listee-106/angular/src/app/error/error500/error500.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { routes } from 'src/app/core/helpers/routes/routes';

@Component({
  selector: 'app-error500',
  templateUrl: './error500.component.html',
  styleUrls: ['./error500.component.css']
})
export class Error500Component {
  public routes = routes;
  constructor(public router: Router){

  }

}

<div class="mainwrapper error-page">
    <div class="content">
     <div class="container">
         <div class="row">
             <div class="col-lg-6 mx-auto">
                 <div class="error-wrap unexpecterror">
                     <div class="error-logo">
                         <a [routerLink]="routes.home1"><img class="img-fluid" src="assets/img/logo.svg" alt="img"></a>
                     </div>
                     <h2>Sorry unexpected Error</h2>
                     <div class="error-img ">
                         <img class="img-fluid" src="assets/img/505error.jpg" alt="img">
                     </div>
                     <a [routerLink]="routes.home1" class="btn btn-primary rounded-pill">Back to Home</a>
                 </div>
             </div>
         </div>
     </div>
 </div>
</div>

// listee-106/vuejs/src/views/pages/Error/error500/Error500.vue
<template>
    <div class="mainwrapper error-page">
	   	<div class="content">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 mx-auto">
						<div class="error-wrap unexpecterror">						
							<div class="error-logo">
								<router-link to="index"><img class="img-fluid" src="../../../../assets/img/logo.svg" alt="img"></router-link>
							</div>
							<h2>Sorry unexpected Error</h2>
							<div class="error-img ">
								<img class="img-fluid" src="../../../../assets/img/505error.jpg" alt="img">
							</div>
							<router-link to="/" class="btn btn-primary rounded-pill">Back to Home</router-link>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>
